### ISSUE TITLE
[R-T5.1-3] Monitor the status of runtime deployment of application in each stage

### ISSUE THREAD

**Issue by giopnd** [radon-h2020/radon-monitoring-tool#5]
| ID  | R-T5.1-3 |
| ------------- | ------------- |
| Section  | USABILITY |
| User Story  | As an Operations Engineer, I want to see the status of runtime deployment of application in each stage |
| Requirement | The runtime toolchain need to provide a status on each stage of deployment of the application on the underlying architecture |
| Extended Description | Using different technologies for monitoring the deployment process, a service or tool must be developed to keep users updated on the status of the deployment process. In case of errors they should be immediatly reported. |
| Affected Tools | Monitoring tool |
| Means of Verification | During runtime execution the log of activites/steps must be available. |
| Dependency | - |

**Comment by gcasale** [comment]
@giopnd please confirm that this requirement is currently met

**Comment by giopnd** [comment]
@gcasale  i actually needed to delete this issue from here since it's a duplicate of https://github.com/radon-h2020/radon-delivery-toolchain/issues/7 (present in delivery toolchain issues). i don't have the rights to delete it.

**Comment by gcasale** [comment]
OK let us close it then.
